id: run_if
namespace: company.team

inputs:
  - id: run_everything
    type: BOOLEAN
    defaults: true

tasks:
  - id: step1
    type: io.kestra.plugin.core.log.Log
    message: "This will always run"

  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.run_everything == true }}"
    then:
      - id: step2
        type: io.kestra.plugin.core.log.Log
        message: "This will only run if set to true"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 10 * * *
    inputs:
      run_everything: true
