id: ssh_git_sync_password
namespace: company.team

tasks:
  - id: connect_to_ssh
    type: io.kestra.plugin.fs.ssh.Command
    host: whisper.pi.willr.uk
    authMethod: PASSWORD
    username: wrussell
    password: "{{ kv('SSH_PASSWORD') }}"
    commands:
      - cd /home/wrussell/ssh-example
      - git pull
      - chmod +x deployment.sh
      - ./deployment.sh

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 7 * * *"