id: anthropic_demo
namespace: company.team

inputs:
  - id: location
    type: STRING
    defaults: London

tasks:
  - id: get_weather
    type: io.kestra.plugin.core.http.Request
    uri: "https://api.openweathermap.org/data/2.5/weather?q={{inputs.location}}&appid={{kv('OPENWEATHERMAP_API_KEY')}}&units=metric"

  - id: chat_completion
    type: io.kestra.plugin.anthropic.ChatCompletion
    apiKey: "{{ kv('ANTHROPIC_API_KEY') }}"
    model: "claude-3-5-sonnet-20241022"
    maxTokens: 1024
    system: "You're a helpful assistant who is going to help plan the day ahead. I'm going to ask a number of questions but I want the final response to be a morning summary of the day in a friendly manner."
    messages:
      - type: USER
        content: "What is the weather like in London? I fetched weather data from OpenWeatherMap Weather API. Use the data from that JSON response to summarise the weather for my morning summary to help me decide what I should wear for the day. The response is {{ outputs.get_weather.body }}"
      - type: USER
        content: "I need to commute from Cambridge train station in London to 10 Downing Street for 9am arrival. What time should I leave for public transport?"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"
