id: modal_s3_alert
namespace: company.team

tasks:
  - id: slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ kv('SLACK_WEBHOOK') }}"
    payload: |
        {
          "text": "New report available! Download it http://localhost:8086/ui/executions/{{flow.namespace}}/{{flow.id}}/{{ execution.id }}."
        }

triggers:
  - id: s3_trigger
    type: io.kestra.plugin.aws.s3.Trigger
    bucket: kestra-modal-example
    interval: PT1S
    prefix: forecast.html
    accessKeyId: "{{ kv('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ kv('AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ kv('AWS_DEFAULT_REGION') }}"    
    action: MOVE
    moveTo:
      key: archive
      bucket: kestra-modal-example
