id: example
namespace: disabled
disabled: true

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Kestra team wishes you a great day! 👋

triggers:
  - id: fail_every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"