id: simple_etl
namespace: company.team

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    beforeCommands:
      - pip install pandas
      - pip install kestra
    script: |
      import pandas as pd
      from kestra import Kestra

      df = pd.read_csv('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv')
      total_revenue = df['total'].sum()
      Kestra.outputs({"total": total_revenue})

  - id: slack_message
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ kv('SLACK_WEBHOOK') }}"
    payload: |
      {
        "text": "Total: ${{ outputs.code.vars.total }}"
      }

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"