id: kafka_realtime_trigger
namespace: company.team

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      id: "{{ trigger.key }}"

  - id: ship_item
    type: io.kestra.plugin.core.log.Log
    message: |
      📦 SHIPPING ALERT - {{ trigger. key }}:
      - Order ID: {{ trigger.value | jq('.order_id') | first }}
      - Item: {{ trigger.value | jq('.item') | first }}
      - Customer: {{ trigger.value | jq('.customer') | first }}
      - Status: PRIORITY HANDLING

triggers:
  - id: listen_to_kafka
    type: io.kestra.plugin.kafka.RealtimeTrigger
    topic: inbound_orders
    groupId: kestra-listener-group
    properties:
      bootstrap.servers: kafka:29092
    keyDeserializer: STRING
    valueDeserializer: JSON