id: 13_advent
namespace: advent

tasks:
  - id: pull_repo
    type: io.kestra.plugin.fs.ssh.Command
    host: whisper.pi.willr.uk
    authMethod: PUBLIC_KEY
    username: wrussell
    privateKey: "{{ secret('SSH_KEY') }}"
    commands:
      - cd /home/wrussell/ssh-example
      - git pull

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: abcdefg