id: oss_spotlight
namespace: company.team

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    containerImage: ghcr.io/kestra-io/pydata:latest
    beforeCommands:
      - pip install kestra
    outputFiles:
      - processed_orders.csv
    script: |
      import pandas as pd
      from kestra import Kestra

      df = pd.read_csv('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv')
      total_revenue = df['total'].sum()

      df['discounted_total'] = df['total'] * 0.9
      df.to_csv('processed_orders.csv')

      Kestra.outputs({"total": total_revenue})

  - id: log_output
    type: io.kestra.plugin.core.log.Log
    message: "Total: ${{ outputs.code.vars.total }}"

  - id: s3_upload
    type: io.kestra.plugin.aws.s3.Upload
    region: eu-west-2
    bucket: oss-example
    key: "processed_orders.csv"
    from: "{{ outputs.code.outputFiles['processed_orders.csv']}}"
    accessKeyId: "{{ kv('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ kv('AWS_SECRET_KEY_ID') }}"
    
errors:
  - id: slack_notification
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ kv('SLACK_WEBHOOK') }}"
    channel: "#general"
    executionId: "{{ execution.id }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
