id: s3_trigger
namespace: company.team

variables:
  source_prefix: inbox
  destination_prefix: archive
  bucket: s3-trigger-example

tasks:
  - id: process_file
    type: io.kestra.plugin.scripts.shell.Commands
    inputFiles:
      file.txt: "{{ trigger.objects[0].uri }}"
    commands:
      - "ls"

  - id: send_alert
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "text": "File: {{ read(trigger.objects[0].uri) }}"
      }

triggers:
  - id: watch
    type: io.kestra.plugin.aws.s3.Trigger
    interval: "PT1S"
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_KEY_ID') }}"
    region: "eu-west-2"
    bucket: "{{ vars.bucket }}"
    action: MOVE
    moveTo:
      key: "{{ vars.destination_prefix }}/{{ vars.source_prefix }}"
      bucket: "{{ vars.bucket }}"
    maxKeys: 1
