id: everything_from_ui
namespace: company.team

triggers:
  - id: watch
    type: io.kestra.plugin.aws.s3.Trigger
    interval: "PT60S"
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_KEY_ID') }}"
    region: "eu-west-2"
    bucket: "will-example"
    action: DELETE
    filter: FILES
    maxKeys: 1

tasks:
  - id: upload
    type: io.kestra.plugin.googleworkspace.drive.Upload
    contentType: text/csv
    from: "{{ trigger.objects[0].uri }}"
    name: Orders
    parents:
      - 1nTsmmL3dMGNmxhU9UrE5UYGxh5LXbcNI
    serviceAccount: "{{ secret('GOOGLE_SERVICE_ACCOUNT') }}"
    mimeType: application/vnd.google-apps.spreadsheet

outputs:
  - id: url
    type: URI
    value: https://docs.google.com/spreadsheets/d/{{ outputs.upload.file.id }}
    displayName: Google Sheets URL
